module.exports = [
    '#version 300 es',
    '#pragma phaserTemplate(shaderName)',
    'precision mediump float;',
    'out vec4 fragColorOutput;',
    'uniform sampler2D uMainSampler;',
    'uniform sampler2D uDisplacementSampler;',
    'uniform vec2 amount;',
    'in vec2 outTexCoord;',
    '#pragma phaserTemplate(fragmentHeader)',
    'void main ()',
    '{',
    '    vec2 disp = (-vec2(0.5, 0.5) + texture(uDisplacementSampler, outTexCoord).rg) * amount;',
    '    fragColorOutput = boundedSampler(uMainSampler, outTexCoord + disp).rgba;',
    '}',
].join('\n');
