module.exports = [
    '#version 300 es',
    '#pragma phaserTemplate(shaderName)',
    'precision mediump float;',
    'out vec4 fragColorOutput;',
    'uniform sampler2D uMainSampler;',
    'uniform vec2 resolution;',
    'uniform float amount;',
    'in vec2 outTexCoord;',
    'void main ()',
    '{',
    '    float pixelSize = floor(2.0 + amount);',
    '    vec2 center = pixelSize * floor(outTexCoord * resolution / pixelSize) + pixelSize * vec2(0.5, 0.5);',
    '    vec2 corner1 = center + pixelSize * vec2(-0.5, -0.5);',
    '    vec2 corner2 = center + pixelSize * vec2(+0.5, -0.5);',
    '    vec2 corner3 = center + pixelSize * vec2(+0.5, +0.5);',
    '    vec2 corner4 = center + pixelSize * vec2(-0.5, +0.5);',
    '    vec4 pixel = 0.4 * texture(uMainSampler, center / resolution);',
    '    pixel += 0.15 * texture(uMainSampler, corner1 / resolution);',
    '    pixel += 0.15 * texture(uMainSampler, corner2 / resolution);',
    '    pixel += 0.15 * texture(uMainSampler, corner3 / resolution);',
    '    pixel += 0.15 * texture(uMainSampler, corner4 / resolution);',
    '    fragColorOutput = pixel;',
    '}',
].join('\n');
