module.exports = [
    '#version 300 es',
    '#pragma phaserTemplate(shaderName)',
    'precision mediump float;',
    'out vec4 fragColorOutput;',
    'uniform sampler2D uMainSampler;',
    'uniform vec4 edge1;',
    'uniform vec4 edge2;',
    'uniform vec4 invert;',
    'in vec2 outTexCoord;',
    'void main ()',
    '{',
    '    vec4 color = texture(uMainSampler, outTexCoord);',
    '    color = clamp((color - edge1) / (edge2 - edge1), 0.0, 1.0);',
    '    color = mix(color, 1.0 - color, invert);',
    '    fragColorOutput = color;',
    '}',
].join('\n');
