module.exports = [
    '#version 300 es',
    '#pragma phaserTemplate(shaderName)',
    '#pragma phaserTemplate(extensions)',
    '#pragma phaserTemplate(features)',
    'precision mediump float;',
    '#pragma phaserTemplate(vertexDefine)',
    'uniform mat4 uProjectionMatrix;',
    'in vec2 inPosition;',
    'in vec2 inLightPosition;',
    'in vec4 inLightColor;',
    'in float inLightRadius;',
    'in float inLightAttenuation;',
    'out vec4 lightPosition;',
    'out vec4 lightColor;',
    'out float lightRadius;',
    'out float lightAttenuation;',
    '#pragma phaserTemplate(outVariables)',
    '#pragma phaserTemplate(vertexHeader)',
    'void main ()',
    '{',
    '    lightColor = inLightColor;',
    '    lightRadius = inLightRadius;',
    '    lightAttenuation = inLightAttenuation;',
    '    lightPosition = uProjectionMatrix * vec4(inLightPosition, 1.0, 1.0);',
    '    gl_Position = uProjectionMatrix * vec4(inPosition, 1.0, 1.0);',
    '    #pragma phaserTemplate(vertexProcess)',
    '}',
].join('\n');
