module.exports = [
    '#version 300 es',
    '#pragma phaserTemplate(shaderName)',
    '#pragma phaserTemplate(extensions)',
    '#pragma phaserTemplate(features)',
    '#ifdef GL_FRAGMENT_PRECISION_HIGH',
    'precision highp float;',
    '#else',
    'precision mediump float;',
    '#endif',
    '#pragma phaserTemplate(fragmentDefine)',
    'out vec4 fragColorOutput;',
    'in vec2 outTexCoord;',
    '#pragma phaserTemplate(fragmentInVariables)',
    '#pragma phaserTemplate(fragmentHeader)',
    'void main ()',
    '{',
    '    vec4 fragColor = vec4(outTexCoord.xyx, 1.0);',
    '    #pragma phaserTemplate(fragmentProcess)',
    '    fragColorOutput = fragColor;',
    '}',
].join('\n');
